# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguadedios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='clave',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='usuario',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
