# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguadedios', '0003_auto_20171125_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrios',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
