# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguadedios', '0004_auto_20171125_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
